### ISSUE TITLE
smarter domain concatenation and broadcast

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#110]
At the moment, the DomainConcatentation class will convert any Scalar children to vectors. This should be generalised, so that if the `evaluate` of its children return a scalar, this is appropriately mapped to a vector at run-time (i.e. for time dependent functions)

**Comment by tinosulzer** [comment]
This issue should:
- unskip the test from #149 
- remove the warning from #124 
- implement #155 
- test that concatenation of 2D matrices works as expected, not just 1D vectors (e.g. the matrix representing c as a function of space and time)

**Comment by martinjrobins** [comment]
discussed this in meeting, see result here: https://github.com/tinosulzer/PyBaMM/pull/163#issuecomment-468256714
