### ISSUE TITLE
enable per-equation discretiation

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#129]
depends on #128 

dict of {variable: discretisation} passed as input to base discretisation class. 

The discretiation class passed in the dict handles things like gradient/divergence discretisation + broadcasting

**Comment by Scottmar93** [comment]
Should `compute_diffusivity` which finds the value of the diffusion coefficient at the locations between nodes be specific to the 'FiniteVolume' method? If we were to implement a `FiniteDifference` method, we could still call the same `compute_diffusivity` function to find the the values at the locations between nodes (even though the nodes are now shifted). Not sure of the requirements for `FiniteElement`

**Comment by Scottmar93** [comment]
@tinosulzer suggested that instead of providing spatial methods per equation, we give a spatial_method to each variable.  

With the per equation method we encounter a problem when we try discretise the dict of variables which is of the form: 
```
model.variables = {"c", c, "N", N} 
```
There is no eqn key id to determine which spatial method we should use.

**Comment by tinosulzer** [comment]
I would also suggest giving `spatial_method` the variable names as keys, e.g. if we define 
```python3
c = Variable("concentration", domain=whole_cell)
```
then the spatial method could have keys 
```python3
spatial_method = {"concentration": ..., ...}
```
We could even make more specific variable classes like `Concentration` , `Potential`, etc that are subclasses of `Variable` but give the right name

**Comment by martinjrobins** [comment]
that sounds reasonable. I guess when you pick a certain set of basis functions, you are picking them to represent a certain variable, rather than an equation, so I think it makes sense.

**Comment by martinjrobins** [comment]
> then the spatial method could have keys
> 
> ```python
> spatial_method = {"concentration": ..., ...}
> ```
> 
This seems inconsistent with what we are doing for model.rhs and model.algebraic? We have used the variable object as the key for these, why not spatial_method as well?

**Comment by tinosulzer** [comment]
Yes, good point, better to keep it consistent.
