### ISSUE TITLE
Change NumpyModelConcatenation to DomainConcatenation in FiniteVolume

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#155]
As title says. This will cause errors though so need to figure out why.

**Comment by tinosulzer** [comment]
Having dug into this, maybe `DomainConcatenation` isn't the most appropriate function to use here. 
`DomainConcatenation` assumes that each symbol in the list of children being passed to it has a non-empty domain, which isn't the case in `FiniteVolume.divergence` as the boundary conditions have empty domain (they are just scalars)

**Comment by Scottmar93** [comment]
This issue is solved if we remove DomainConcatenation as you suggest in the discussion in #163. DomainConcatenation is very specific to the macroscale domains which I think we should avoid.

**Comment by martinjrobins** [comment]
discussed this in meeting, see result here: https://github.com/tinosulzer/PyBaMM/pull/163#issuecomment-468256714

**Comment by tinosulzer** [comment]
Closed by #163
