### ISSUE TITLE
Overload addition for Models to allow easy composition of submodels

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#165]
Overload the add operator for Models so that submodels can be easily composed into a full model. This also allows for an easy method of adding new physics / degradation mechanisms to the models

**Comment by Scottmar93** [comment]
this issue has now been changed to: modify the .update method so that it checks .ids of keys in models being combined and also combines the algebraic dict

**Comment by tinosulzer** [comment]
closed by #166
