### ISSUE TITLE
Add a process_variables in discretisation

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#174]
**Summary**
Currently we process model.variables using process_dict. But if this evaluates to a number then we eqn_key.domain is used. This is fine for rhs, etc but for variables  the keys are strings and so have no attribute of this type. 
For model.variables it is probably fine to just output the number instead of broadcasting to a domain so we could just skip this step

**Comment by tinosulzer** [comment]
Yeah I think just add a condition that if `eqn_key` is a string then skip that step
