### ISSUE TITLE
NumpyModelConcatentation 

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#178]
**Describe the bug**
For SPM we now have current=standard_parameters.current_with_time in the boundary condition. But during discretisation NumpyModelConcatenation is called to add boundary conditions. This does an evaluate which requires the time as an input  which isn't defined yet and so raises and error. 

@tinosulzer do you think this will be covered by the #163 ? If so, close this issue.

**Comment by tinosulzer** [comment]
Has this been fixed by #163?

**Comment by Scottmar93** [comment]
Just tried it. It isn't fixed by #163
