### ISSUE TITLE
Symbolic differentiation

### ISSUE THREAD

**Issue by tinosulzer** [tinosulzer/PyBaMM#189]
We need a function (e.g. `pybamm.diff`) that calculates the derivative of an expression tree with respect to a variable. For example, some lead-acid models require the user to provide a function for the open-circuit potential `U(c)` while others require its derivative `dU/dc` (and also for the exchange-current density). 

We could either ask the user to provide the appropriate derivatives manually at the same time as the functions themselves, or calculate the derivative using the expression tree and appropriate applications of the chain rule and power rule. I think the latter is safer

**Comment by tinosulzer** [comment]
Autograd is working well for the arbitrary numpy functions, but the drawback is that we have to import `autograd.numpy` instead of `numpy`. Are we happy to force the user to do this?

**Comment by rtimms** [comment]
It looks like `autograd` is probably the easiest tool out there for calculate the Jacobian for use in the solver, which would force us to use `autograd.numpy` anyway. Maybe there are other options, but from what I can see this is probably the simplest fix

**Comment by martinjrobins** [comment]
does that mean that the user *wouldn't* be able to use normal numpy?

**Comment by tinosulzer** [comment]
We could do something like 
```python3
try:
    import autograd.numpy as np
except ModuleNotFoundError:
    import numpy as np
```

Then throw errors/warnings that the functionality provided by autograd (symbolic differentiation, automatic jacobian in #197) can't be used if it's not installed.
Might be best to do this in `__init__.py` and then `pybamm.numpy as np` whenever needed so that we don't need to repeat the above 4 lines every time.

In any case, autograd is easy to install with pip and seems well maintained so it should be fine to just include in `setup.py`

**Comment by martinjrobins** [comment]
seems sensible to start out using autograd for both this issue and #197 and we can see how the PR looks. if we use autograd this should be fairly straightforward to implement

**Comment by tinosulzer** [comment]
I've submitted a PR for this issue

**Comment by tinosulzer** [comment]
Re-opening: need to deal with `FunctionParameter` nodes better
