### ISSUE TITLE
refactor BaseModel to hold an expression tree

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#19]
See #16. 

The base model will internally hold an expression tree representing the rhs of an ode model. e.g.

```python
class BaseModel:
   def __init__(self):
         self._rhs = ... # lhs is a dictionary mapping variables to expressions
         self._initial_conditions = ... # a dictionary mapping expression to expressions representing the initial conditions
         self._boundary_conditions = ... # a dictionary mapping expression to expressions representing the boundary conditions
   @property
   def rhs(self):
          return self._rhs
   ...
```

Note: rather than having `rhs` return a dict, it might be nicer to have `BaseModel` emulate a dictionary, so you could write `model[variable]` and get the rhs expression associated with that variable (see https://docs.python.org/3/reference/datamodel.html?emulating-container-types#emulating-container-types)

**Comment by Scottmar93** [comment]
Maybe I'm am looking to do more than is needed. Will this just end up being a class with three initially empty dictionaries (_rhs, _initial_conditions, and _boundary_conditions), with the model[variable] functionality and setters and getters for each of the dictionaries? Or do I need to consider the interactions with the other submodels and the expression tree? 

I have already done the first of the above and I am currently writing a test and the doc string for it.

**Comment by martinjrobins** [comment]
> Maybe I'm am looking to do more than is needed. Will this just end up being a class with three initially empty dictionaries (_rhs, _initial_conditions, and _boundary_conditions), with the model[variable] functionality and setters and getters for each of the dictionaries? 

Yup, I think that is all that is needed
