### ISSUE TITLE
refactor spatial discretisation class

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#20]
see #16. 

the new spatial discretisation base class and derived classes need to process a Model, along with an input mesh in order to:
   1. count the number of variables needed, and therefore the size of the state vector
   2. replace all `Variable` nodes with `Vector` nodes 
   3. replace all spatial gradient operators with `Matrix` nodes

example use:

```python
model = ReactionDiffusionModel()
param_file = Parameters("file.dat")
param_file.process(model)
disc = FiniteVolumeDiscretisation(mesh_dx=0.1, something_else=2)
y0 = disc.process(model)
```
My current thoughts are that the discretisation class should also generate initial conditions (perhaps from functions contained in the `Variable` nodes of the expression tree?), and output the initial state vector from the `process` function so that it can be used by the solver class

**Comment by tinosulzer** [comment]
Made a start on this (and #23), but more work needed on this issue:
- [ ] discretise `Scalar` based on variable domain (using `IndependentVariable` class?)
- [ ] discretise `Variable` into `Vector` with the correct slice
- [ ] incorporate boundary conditions into discretisation of `rhs`
- [ ] concatenate right-hand sides into a single `dydt` numpy array
- [ ] more testing
