### ISSUE TITLE
add a list of index ranges to `Scalar`, and a value for each range

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#26]
"A Scalar has a list of index ranges, and a value for each range". This is not implemented

**Comment by martinjrobins** [comment]
I've been having a go at this. Basically when you call the evaluate on this node, it should return a vector filled with values at the given ranges. So it might be more efficient to just use the `Vector` node rather than have the `Scalar` node have multiple values

**Comment by tinosulzer** [comment]
> I've been having a go at this. Basically when you call the evaluate on this node, it should return a vector filled with values at the given ranges. So it might be more efficient to just use the `Vector` node rather than have the `Scalar` node have multiple values
> 
> @tinosulzer, you have been doing the discretisation, what do you think? Is this issue necessary or can we just use the `Vector` node?

I think it would be better to just use the `Vector` node, but the size ranges of the vector of the vector won't be known until discretisation. I've created a `Concatenation` class which might help:

1. Create a multi-domain parameter by concatenating single-valued parameters:
```python3
```

**Comment by martinjrobins** [comment]
The concatenation looks nice! Does this mean that `Parameters` should only have a single domain, so that they can always be replaced by a single scalar?

**Comment by tinosulzer** [comment]
Yes, in fact I think domain could just be a string (will always be either `"negative_electrode"`, `"separator"`, `"positive_electrode"` or `"whole_cell"`) rather than a list of strings

**Comment by martinjrobins** [comment]
would it be useful to be able to easily define a single parameter that was valid over multiple domains, but had the same value over those domains?

**Comment by tinosulzer** [comment]
Yes, that would be useful

**Comment by martinjrobins** [comment]
ok. closing this as not needed.
