### ISSUE TITLE
overloaded binary operators on `Symbol` take numbers

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#45]
see #36. It might be useful for the overloaded binary operators on`Symbol` (e.g. `__mul__`) be able to take `Numbers` (e.g. `int'). They would then implicitly convert this to a `Scalar` node.

Note: also need to add `__pow__` to this list.

**Comment by tinosulzer** [comment]
`__pow__` , `__neg__` and `__abs__` also need to be added as methods in the `Symbol` class

**Comment by tinosulzer** [comment]
Should the overloading be inside the `__mul__` function
```python3
def __mul__(self, other):
    if isinstance(other, Symbol):
         return Multiplication(self, other)
    elif isinstance(other, int) or isinstance(other, float):
          return Multiplication(self, Symbol(other))
``` 
or at the start of `BinaryOperators`
```python3
class BinaryOperator(self):
      def __init__(self, name, left, right):
             if isinstance(right, int) or isinstance(right, float):
                   right = Symbol(right)
```
?

**Comment by martinjrobins** [comment]
I think the 2nd option would be better, as then it would work for all the binary operators. 

note that you can check if a python object is any type of number using `numbers.Number`, see https://stackoverflow.com/questions/4187185/how-can-i-check-if-my-python-object-is-a-number

note that if left or right is not a Symbol or a number, then the init should throw

note also that you will want to convert the left input to a Symbol if it is a number as well
