### ISSUE TITLE
Refactor StefanMaxwellDiffusion class

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#49]
This issue must be completed prior to refactoring the reaction diffusion model #17

StefanMaxwellDiffusion should inherit from BaseModel so that it is a complete model in its own right. It will contain a dictionary with the set of equations in the electrolyte implemented in symbolic form employing the expression tree. 

Will looks something like:

```
class StefanMaxwellDiffusion(BaseModel): 
        def __init__(self): 
            self._rhs = {c: "epression"}
            self._initial_conditions = .... etc 

           self._variable = {"c": c, ...} 
```

EDIT. 
The keys should be of class Symbol expect for the _variable dictionary.

**Comment by tinosulzer** [comment]
Yep looks good - the keys and variables of _rhs, etc should be Symbols though:
```
class StefanMaxwellDiffusion(BaseModel): 
        def __init__(self):
            c = Variable("c", domain=["whole cell"]
            N = ...
            expression = ...
            self._rhs = {c: expression}
            self._initial_conditions = {c: ...}
            self._boundary_conditions = {N: (left bc, right bc)}
            self._variables = {"c": c, "N": N}
```

**Comment by Scottmar93** [comment]
I am unsure what tests are appropriate to run on this class. 

I have push what I have done so far if anyone wants to take a look/take over

**Comment by tinosulzer** [comment]
Cheers Scott, looking good. Very basic tests could be just making sure that `model = pybamm.ReactionDiffusionModel()` doesn't throw any errors (e.g. with `G = Scalar(1)`), then seeing if you can process the model with appropriate parameters and discretisation, and finally something along the lines of the functions currently in `test_reaction_diffusion.py` to make sure that the input/output has the right shape and the model behaves physically as expected
