### ISSUE TITLE
Add DAE option to solver

### ISSUE THREAD

**Issue by tinosulzer** [tinosulzer/PyBaMM#5]
Add a new solver class DAESolver
- [ ] Import SUNDIALS (or other) in Dockerfile 
- [ ] Tell the solver which equations are ODEs and which are algebraic; I think this should be done by the model class
- [ ] Write DAESolver class to solve the DAE system

**Comment by tinosulzer** [comment]
@martinjrobins @fcooper8472 do either of you know how to install SUNDIALS in travis?

**Comment by martinjrobins** [comment]
we should be able to install the serial version of SUNDIALS through apt, see https://github.com/travis-ci/apt-package-safelist/pull/1651. So that should make it easy for testing.

**Comment by martinjrobins** [comment]
then use the python interface for sundials: https://pypi.org/project/python-sundials/

We'd need to add sundials as a dependency for PyBaMM as well

**Comment by martinjrobins** [comment]
might want to use scipy.odes: https://scikits-odes.readthedocs.io/en/latest/installation.html

**Comment by martinjrobins** [comment]
having trouble installing scipy.odes. Raised an issue in their repo to see if they can solve it

**Comment by martinjrobins** [comment]
installing scikits.odes broken with pip 19, works with pip 18, seems to be pips fault.

**Comment by tinosulzer** [comment]
Ok, is "works with pip 18" good enough (with hope that pip 19 will be fixed at some point) or are we worried it will put people off?

**Comment by martinjrobins** [comment]
Looks like this is a fairly recent pip issue:

https://github.com/pypa/pip/issues/6163

it is marked as a bug, so presumably will be fixed, hopefully soon!
