### ISSUE TITLE
Refactor HomogenousReactions class

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#51]
This is a pre-requisite for #17 

Refactor this class to that it simply returns an symbolic expression for the Homogeneous reactions. 

Should this really be a class? A function is probably sufficient

**Comment by tinosulzer** [comment]
Agree that a function should be sufficient. 

Another prerequisite for this is defining an appropriate current function `icell(t)` (note that we already have a class for the independent variable `t` in the expression tree).

**Comment by Scottmar93** [comment]
requires #67 so that can have: 
`G = (Scalar(1,"negative electrode"), Scalar(0, "separator"), Scalar(-1,"positive electrode") `
Where `G` is the flux between electrode and electrolyte.

**Comment by Scottmar93** [comment]
requires #68 for time dependent homogeneous reaction rate.
