### ISSUE TITLE
Using Binary Operations

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#52]
Getting issues when trying to write
```
c = Variable('c') 
 1 - c  
```
and also 
```
 -c 
```

Does the BinaryOperator class account for the case of integer inputs or no input on one side but symbols on the other?

**Comment by Scottmar93** [comment]
I see Scalar(1)  and Scalar(0) could be used here but seems clunky

**Comment by tinosulzer** [comment]
See #45 - could be a good issue to work on to learn how the expression tree works
