### ISSUE TITLE
discritisation of boundary conditions

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#63]
I was just looking at the discretisation of the boundary conditions. At the moment this seems to be mainly done in the `gradient` and `divergence` functions of `MatrixVectorDiscretisation`, which both do this:

```python
       # Add boundary conditions if defined
        if symbol.id in boundary_conditions:
            lbc, rbc = boundary_conditions[symbol.id]
            discretised_symbol = self.concatenate(lbc, discretised_symbol, rbc)
        gradient_matrix = self.gradient_matrix(domain)
        return gradient_matrix * discretised_symbol
```
So it looks like extra ghost nodes are added to the current state vector to implement the bc. Should this be done instead when the `pybamm.Variable` node is processed in `process_symbol`? Also, the way the boundary conditions are implemented would depend on the method, so this should probably be done in `FiniteVolumeDiscretisation`? @tinosulzer?

**Comment by tinosulzer** [comment]
Yes, this is quite hacky as currently implemented: for example, there will be errors with matrix sizes if no boundary conditions are given. Moving to `FiniteVolumeDiscretisation` seems sensible for now but we should discuss how to do this properly

**Comment by martinjrobins** [comment]
After meeting (14/1/19):
- [ ] add checks in Discretisation that there are either Dirichlet or Neumann bcs for each fundamental vector
- [ ] add support for Dirichlet bc.  concatenate appropriate ghost nodes on StateVector
