### ISSUE TITLE
allow concatenation of variables and scalars

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#80]
From @tinosulzer  in #77:

It would useful to allow concatenation of variables and scalars, to deal with a case like the following:
Interfacial current G is some function in the positive and negative electrodes, and zero in the separator. In the model, this would probably be coded as

Gn = cn ** 2
Gs = Scalar(0)
Gp = cp ** 3
G = Concatenation(Gn, Gs, Gp)
Then G should get discretised to a concatenation of an expression tree with a StateVector, representing cn, for the negative electrode, a Vector of zeros with the right shape, and an expression tree StateVector, representing cp, for the positive electrode.

**Comment by martinjrobins** [comment]
To implement this, I would propose that when the discretisation class come across a `Concatenate`, then it:
   1. checks if any of the children expressions vary with time (i.e. have variables in them)
   2. if any children *don't* vary with time, then work out the domain of that child and the value it evaluates to, and replace the child with a Vector of the right shape
   3. if all children don't vary with time, then replace the concatenate by a concatenated Vector
   4. if any children vary with time, replace the Concatentate with a NumpyConcatenate

**Comment by tinosulzer** [comment]
For 1., it might be useful to differentiate between functions that need a `t` and `y` input in `evaluate`, and those that just have a `value` (Scalars, Vectors, Matrices). 
e.g. a `Multiplication` of two nodes that both have a value could itself get a value.
This is stepping a bit into the territory of issue #54 though

**Comment by martinjrobins** [comment]
agreed. Whichever is done first, this one or #54, should implement a test to see if you can evaluate an expression without `t` or `y`, then we could use this for both.

**Comment by tinosulzer** [comment]
this needs to be done before #51 (which in turn needs to be done before #17)
