### ISSUE TITLE
Give domain to all expressions

### ISSUE THREAD

**Issue by tinosulzer** [tinosulzer/PyBaMM#82]
Currently, only `Variable`, `Parameter` and `Scalar` nodes have domains. It would be useful to be able to evaluate the domain of an arbitrary node, e.g. `2*var` which is a Multiplication.
Proposed edit is:
- For a `UnaryOperator`, inherit domain from child (can be `None`)
- For a `BinaryOperator`, check that children have the same domain (or either or both `None`) and inherit that domain
- Additionally, check that key and value have the same domain in `model.rhs` and `model.initial_conditions` (via the respective setters in `BaseModel`)

This will help with #78 , and allow us to not have to pass `domain` as an argument in the discretisation functions.
@martinjrobins thoughts on this?

**Comment by martinjrobins** [comment]
Yes, this would be really good, and would help with #80 as well.

presumably if you `Concatenate` two or more expressions you add their domains into a combined list? How do you know when you get to "whole cell" though?

**Comment by tinosulzer** [comment]
Yes, agree with that approach for Concatenate. 
For now we could treat ["negative electrode", "separator", "positive electrode"] and ["whole cell"] as equal, but maybe ["whole cell"] should be deprecated

**Comment by tinosulzer** [comment]
What is the intended functionality of having a separate `Domain` class? Could we make `domain` (+ setters and getters) an attribute of `Symbol`? I'm struggling with multiple inheritance ...

**Comment by martinjrobins** [comment]
if everything is going to have a domain, then it makes sense to merge the `Domain` class with the base `Symbol` class, so I'm happy if you want to do this rather than have multiple inheritance
