### ISSUE TITLE
Constrain combined domains

### ISSUE THREAD

**Issue by tinosulzer** [tinosulzer/PyBaMM#85]
As suggested by @martinjrobins in #83 : 

> If you write:
> 
> a = Scalar(3, domain=["negative electrode"]
> b = Scalar(4, domain=["positive electrode"]
> c = Scalar(5, domain=["separator"]
> eq = Concatenate(a,b,c)
> the domain of eq will be ["negative electrode", "positive electrode", "separator"]. But with
> 
> a = Scalar(3, domain=["negative electrode"]
> b = Scalar(4, domain=["positive electrode"]
> c = Scalar(5, domain=["separator"]
> eq = Concatenate(a,c,b)
> the domain will be identified as ["whole cell"]
> 
> Plus in discretisation the resultant Vector is different between the two concatenations.
>
> We could either impose an ordering on combined domains, or it could be the responsibility of the model creator. The former is preferable I think (might want to open another issue for this).

I agree that imposing a constraint is preferable. Best place is probably in the `domain` setter in `Symbol`, so that it also catches domains that have been created in the wrong order. 
Should raise a `DomainError` if domains are given in the wrong order.

**Comment by martinjrobins** [comment]
I'm going to the the sequence of `KNOWN_DOMAINS` as the ordering constraint, so if a model writer tries to use another ordering (e.g. ["separator", "negative domain"]) an error is thrown. Any concatentation of domains will result in a reordering so that the order matches the sequence in `KNOWN_DOMAINS`
