### ISSUE TITLE
Improve tree visualisation

### ISSUE THREAD

**Issue by Scottmar93** [tinosulzer/PyBaMM#87]
**Summary**
Add a method to visualize the tree within an svg file. 

**Reason** 
Is useful for demonstrating what the code is doing and for a user to make manual checks on inputted models.

**Comment by martinjrobins** [comment]
note this should just be a matter of calling the right anytree functions

e.g. https://anytree.readthedocs.io/en/2.4.3/exporter/dotexporter.html

**Comment by martinjrobins** [comment]
see examples here:

https://stackoverflow.com/questions/49333295/rendering-a-tree-in-python-using-anytree-and-graphviz-without-merging-common-no
