### ISSUE TITLE
Add mesh and operators for spherical domain

### ISSUE THREAD

**Issue by tinosulzer** [tinosulzer/PyBaMM#9]
**Summary**
- Add (dimensionless?) spherical domain to mesh.py, independently of the existing Cartesian domain
- Add grad and div operators (Finite Volumes) for the spherical domain

**Comment by tinosulzer** [comment]
With the new expression tree structure this requires:
- a new class FiniteVolumeMicroMesh (or could just make a single FiniteVolumeMesh) with submeshes "negative particle" and "positive particle"
- new methods (or a separate class) for spherical gradient and divergence at the microscale

**Comment by Scottmar93** [comment]
Mesh shall be unchanged. Will use `if domain is "negative particle" or "positive particle"` to determine when spherical operators should be used.

**Comment by tinosulzer** [comment]
Closed by #142
